export const ROUTES_OF_WHITE_BACKGROUND_PAGE = [
  '/about',
  '/place/details',
  '/reviews',
  '/notification',
  '/schedules',
  '/schedules/detail',
  '/qna',
  '/profile',
  '/profile/edit',
  '/travel-history',
  '/destinations/list',
  '/destinations/create',
  '/destinations/update',
  '/members/list',
  '/members/create',
  '/members/update',
]
