name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

concurrency:
  group: "azure-static-web-apps"
  cancel-in-progress: true

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Build with Docker
        id: build
        run: |
          docker build -t app-builder --target builder .
          docker create --name app-container app-builder
          docker cp app-container:/app/dist ./dist
          docker rm app-container

      - name: Deploy to Azure
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_DESERT_0DB2C0F00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'
          output_location: 'dist'
